name: Upgrade pip

on: [push]  # or any other event that triggers this workflow

jobs:
  upgrade-pip:
    runs-on: ubuntu-latest  # or any other suitable runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Upgrade pip
      run: /home/adminuser/venv/bin/python -m pip install --upgrade pip
